org.gradle.caching=true
org.gradle.parallel=true
# Re-enable once the build supports Isolated Projects and IDEA-389678 is fixed:
# https://youtrack.jetbrains.com/issue/IDEA-389678
org.gradle.tooling.parallel=false
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8

kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true

kotlin.code.style=official
