[versions]

version-name = "0.3.0"

java-compiler-version = "25"
java-library-bytecode-version = "11"
java-plugin-bytecode-version = "17"

versions-plugin = "0.61.0"
dokka = "2.2.0"
gradle-maven-publish-plugin = "0.37.0"

kotlin = "2.4.10"
kotlinter = "5.6.0"

kotlinx-atomic-fu = "0.33.0"
kotlinx-benchmark = "0.4.18"
kotlinx-coroutines = "1.11.0"

[plugins]

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish-plugin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

conventions-kmp = { id = "kmp-conventions" }
conventions-kotlin = { id = "kotlin-conventions" }
conventions-gradle-plugin = { id = "gradle-plugin-conventions" }
conventions-linting = { id = "linting-conventions" }
conventions-publishing = { id = "publishing-conventions" }
conventions-versions = { id = "versions-conventions" }

[libraries]

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

kotlinx-atomic-fu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomic-fu" }
kotlinx-benchmark = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradle-maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradle-maven-publish-plugin" }
gradle-versions-plugin = { module = "io.github.ben-manes:gradle-versions-plugin", version.ref = "versions-plugin" }
kotlinter-gradle-plugin = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
