name: Benchmark ⌛

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: false
  workflow_dispatch:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: write
    steps:

      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set up jdk@21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew benchmark

      - name: Move benchmark files
        run: |
          mkdir -p benchmark  # This command ensures that the 'benchmark' directory exists
          find . -type f \( -iname '*benchmark.json' -o -iname '*benchmark.csv' \) -exec mv {} ./benchmark/ \;

      - name: Commit benchmark files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add benchmark/*
          git commit -m "Commit benchmark results" -a
          git push
