name: Build 🔨

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: false
  workflow_dispatch:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:

      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set up jdk@21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build
