name: Pull Request Comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  benchmark:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/benchmark')
    permissions:
      contents: write
    with:
      runner: macos-13
    uses: ./.github/workflows/benchmark.yml
