name: Pull Request Comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  derive-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-output.outputs.value }}
    steps:
      - id: set-output
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

  benchmark:
    needs: derive-branch
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/benchmark')
    permissions:
      contents: write
    with:
      runner: macos-13
      branch: ${{ needs.derive-branch.outputs.branch }}
      should-commit-benchmark: true
    uses: ./.github/workflows/benchmark.yml

