name: Pull Request Comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  benchmark:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/benchmark')
    runs-on: macos-13
    permissions:
      contents: write
    steps:

      - name: Derive branch name
        id: derive-branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Run Benchmark
        with:
          runner: macos-13
          branch: ${{ steps.derive-branch.outputs.branch }}
          should-commit-benchmark: true
        uses: ./.github/workflows/benchmark.yml
