name: CI for main

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    uses: ./.github/workflows/build.yml
    with:
      runner: ${{ matrix.os }}
