name: CI for main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read

jobs:

  lint:
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: ubuntu-24.04-arm
      task: lintKotlin
    secrets:
      gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  metadata:
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: ubuntu-24.04-arm
      task: compileCommonMainKotlinMetadata
    secrets:
      gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: JVM (Linux ARM64)
            os: ubuntu-24.04-arm
            task: jvmTest
          - name: Linux ARM64
            os: ubuntu-24.04-arm
            task: linuxArm64Test
          - name: Linux x64
            os: ubuntu-latest
            task: linuxX64Test
          - name: macOS and iOS Simulator ARM64
            os: macos-latest
            task: macosArm64Test iosSimulatorArm64Test
          - name: Apple compatibility compilation
            os: macos-latest
            task: compileKotlinMacosX64 compileKotlinIosX64 compileKotlinIosArm64
          - name: MinGW x64
            os: windows-latest
            task: mingwX64Test
    name: ${{ matrix.name }}
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: ${{ matrix.os }}
      task: ${{ matrix.task }}
    secrets:
      gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
