name: Pull Request and Merge Workflow

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'benchmark/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    uses: ./.github/workflows/build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      runner: ${{ matrix.os }}
